```{r set-options, echo=FALSE, cache=FALSE}
options(width=200)
```
```{r, echo = FALSE}
#Get the compound name
compound = readRDS("compound.rds")
```
Dilution Sheet for `r compound`
========================================================
```{r, echo=FALSE, warning=FALSE}
#Determine whether a stock needs to be made
stockmake = readRDS("stockmake.rds")
#Get the recipe
recipe = readRDS("recipe.rds")
#See if the stock solution is contrated enough to make any of the dilutions
brake = readRDS("brake.rds")
#Get the desired final concentration
concentration = readRDS("concentration.rds")
#Read in the highRecipe file
if (file.exists("highRecipe.rds")){
  highRecipe = readRDS("highRecipe.rds")
  nrowHR = nrow(highRecipe)
} else {
    nrowHR = 0
}

rows = nrowHR + nrow(recipe)

#Round the recipe columns to pipettable volumes
roundVolume = function(x){
    if(x <= 2){
        return(as.character(round(x,3)))
    } else if(x <= 20){
        return(as.character(round(x,2)))
    } else if(x <= 200){
        return(as.character(round(x,1)))
    } else {
        return(as.character(round(x,0)))
    }    
}

#Get the raw amounts for the lysate and s medium
recipe[,5] = as.numeric(as.character(recipe[,5]))
recipe[,3] = as.numeric(as.character(recipe[,3]))
rawLysate = as.numeric(as.character(rows*recipe[,5]))
rawSmed = as.numeric(as.character(rows*recipe[1,3]))

#Adjust for pipetiing error (make a little extra)
adjLysate = rawLysate[1] * (1+(1/60))
tot = adjLysate * 10
adjSmed = tot - adjLysate
slmix = paste(round(adjLysate + adjSmed,0), " µL.")

#Round the recipe values
recipe[,c(3,4,6)] = sapply(recipe[,c(3,4,6)], roundVolume)

#Space out the columns by adding spaces in the column titles
for (i in seq(1,length(recipe))){
  colnames(recipe)[i] = sprintf("%03s",colnames(recipe)[i])
}
```

Stock solution:

```{r, echo = FALSE}
stockmake
```

Total K Medium/Lysate mix:

```{r, echo = FALSE}
mixline = paste0("K Medium: ", as.character(round(adjSmed,0)), "   Lysate: ", as.character(round(adjLysate,0)))
mixline
```

Dilute down to final concentrations:

```{r, echo = FALSE}
if (brake == TRUE){
  print("The stock dilution is not concentrated enough.")
}
if (brake == FALSE){
  print(recipe[,c(1,2,3,4,6)])
}
```

Use higher stock (if necessary):

```{r, echo = FALSE, warning = FALSE}
if (file.exists("highRecipe.rds")){
  highRecipe = readRDS("highRecipe.rds")
  if(typeof(highRecipe) == "list"){
    highRecipe[,c(3,4,6)] = sapply(highRecipe[,c(3,4,6)], roundVolume)
    print(highRecipe[,c(1,2,3,4,6)])
  } else {
    print(highRecipe)
  }
} else {
  print("Not necessary")
}
```


